import Head from 'next/head'
import Link from 'next/link'
import styles from './Layout.module.css'

const Layout = ({ children, title = 'World Ranks' }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/img/favicon.png" />
            </Head>
            <header className={styles.header}>
                <Link href="/">
                    <img src="/img/logo.svg" alt="logo" />
                </Link>
            </header>
            <main className={styles.main}>{children}</main>

            <footer className={styles.footer}>Rafael Barros @ github.com/BarrosAmorim</footer>
        </div>
    )
}

export default Layout
